var annotated_dup =
[
    [ "__clove_cmdline_t", "struct____clove__cmdline__t.html", "struct____clove__cmdline__t" ],
    [ "__clove_generic_u", "union____clove__generic__u.html", "union____clove__generic__u" ],
    [ "__clove_map_node_t", "struct____clove__map__node__t.html", "struct____clove__map__node__t" ],
    [ "__clove_map_params_t", "struct____clove__map__params__t.html", "struct____clove__map__params__t" ],
    [ "__clove_map_t", "struct____clove__map__t.html", "struct____clove__map__t" ],
    [ "__clove_report_json_t", "struct____clove__report__json__t.html", "struct____clove__report__json__t" ],
    [ "__clove_report_list_tests_csv_t", "struct____clove__report__list__tests__csv__t.html", "struct____clove__report__list__tests__csv__t" ],
    [ "__clove_report_list_tests_json_t", "struct____clove__report__list__tests__json__t.html", "struct____clove__report__list__tests__json__t" ],
    [ "__clove_report_list_tests_pretty_t", "struct____clove__report__list__tests__pretty__t.html", "struct____clove__report__list__tests__pretty__t" ],
    [ "__clove_report_list_tests_t", "struct____clove__report__list__tests__t.html", "struct____clove__report__list__tests__t" ],
    [ "__clove_report_params_t", "struct____clove__report__params__t.html", "struct____clove__report__params__t" ],
    [ "__clove_report_pretty_t", "struct____clove__report__pretty__t.html", "struct____clove__report__pretty__t" ],
    [ "__clove_report_run_tests_csv_t", "struct____clove__report__run__tests__csv__t.html", "struct____clove__report__run__tests__csv__t" ],
    [ "__clove_report_t", "struct____clove__report__t.html", "struct____clove__report__t" ],
    [ "__clove_stack_t", "struct____clove__stack__t.html", "struct____clove__stack__t" ],
    [ "__clove_stream_console_t", "struct____clove__stream__console__t.html", "struct____clove__stream__console__t" ],
    [ "__clove_stream_file_t", "struct____clove__stream__file__t.html", "struct____clove__stream__file__t" ],
    [ "__clove_stream_memory_t", "struct____clove__stream__memory__t.html", "struct____clove__stream__memory__t" ],
    [ "__clove_stream_t", "struct____clove__stream__t.html", "struct____clove__stream__t" ],
    [ "__clove_string_view_t", "struct____clove__string__view__t.html", "struct____clove__string__view__t" ],
    [ "__clove_suite_t", "struct____clove__suite__t.html", "struct____clove__suite__t" ],
    [ "__clove_symbols_context_t", "struct____clove__symbols__context__t.html", "struct____clove__symbols__context__t" ],
    [ "__clove_symbols_function_t", "struct____clove__symbols__function__t.html", "struct____clove__symbols__function__t" ],
    [ "__clove_test_expr_t", "struct____clove__test__expr__t.html", "struct____clove__test__expr__t" ],
    [ "__clove_test_t", "struct____clove__test__t.html", "struct____clove__test__t" ],
    [ "__clove_time_t", "struct____clove__time__t.html", "struct____clove__time__t" ],
    [ "__clove_vector_params_t", "struct____clove__vector__params__t.html", "struct____clove__vector__params__t" ],
    [ "__clove_vector_t", "struct____clove__vector__t.html", "struct____clove__vector__t" ]
];